'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServicioCancelacionCFDI
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioCancelacionCFDI.CancelacionServiceSoap")>  _
    Public Interface CancelacionServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelarCFDI", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelarCFDI(ByVal rfc As String, ByVal serie As String, ByVal folio As Long) As ServicioCancelacionCFDI.OutputOfCancelar
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelarCFDI", ReplyAction:="*")>  _
        Function CancelarCFDIAsync(ByVal rfc As String, ByVal serie As String, ByVal folio As Long) As System.Threading.Tasks.Task(Of ServicioCancelacionCFDI.OutputOfCancelar)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelarCFDI_UUID", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelarCFDI_UUID(ByVal rfc As String, ByVal uuid As String) As ServicioCancelacionCFDI.OutputOfCancelar
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelarCFDI_UUID", ReplyAction:="*")>  _
        Function CancelarCFDI_UUIDAsync(ByVal rfc As String, ByVal uuid As String) As System.Threading.Tasks.Task(Of ServicioCancelacionCFDI.OutputOfCancelar)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class OutputOfCancelar
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private resultadoField As String
        
        Private idField As Integer
        
        Private objetoField As Cancelar
        
        Private colleccionField() As Cancelar
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Resultado() As String
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
                Me.RaisePropertyChanged("Resultado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Objeto() As Cancelar
            Get
                Return Me.objetoField
            End Get
            Set
                Me.objetoField = value
                Me.RaisePropertyChanged("Objeto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=3)>  _
        Public Property Colleccion() As Cancelar()
            Get
                Return Me.colleccionField
            End Get
            Set
                Me.colleccionField = value
                Me.RaisePropertyChanged("Colleccion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Cancelar
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private id_ComprobanteField As Integer
        
        Private estatusField As Integer
        
        Private uuidField As String
        
        Private fechaField As Date
        
        Private acuseField() As Byte
        
        Private id_ProveedorField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Id_Comprobante() As Integer
            Get
                Return Me.id_ComprobanteField
            End Get
            Set
                Me.id_ComprobanteField = value
                Me.RaisePropertyChanged("Id_Comprobante")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Estatus() As Integer
            Get
                Return Me.estatusField
            End Get
            Set
                Me.estatusField = value
                Me.RaisePropertyChanged("Estatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
                Me.RaisePropertyChanged("Uuid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("Fecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=4)>  _
        Public Property Acuse() As Byte()
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
                Me.RaisePropertyChanged("Acuse")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Id_Proveedor() As Integer
            Get
                Return Me.id_ProveedorField
            End Get
            Set
                Me.id_ProveedorField = value
                Me.RaisePropertyChanged("Id_Proveedor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CancelacionServiceSoapChannel
        Inherits ServicioCancelacionCFDI.CancelacionServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CancelacionServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicioCancelacionCFDI.CancelacionServiceSoap)
        Implements ServicioCancelacionCFDI.CancelacionServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CancelarCFDI(ByVal rfc As String, ByVal serie As String, ByVal folio As Long) As ServicioCancelacionCFDI.OutputOfCancelar Implements ServicioCancelacionCFDI.CancelacionServiceSoap.CancelarCFDI
            Return MyBase.Channel.CancelarCFDI(rfc, serie, folio)
        End Function
        
        Public Function CancelarCFDIAsync(ByVal rfc As String, ByVal serie As String, ByVal folio As Long) As System.Threading.Tasks.Task(Of ServicioCancelacionCFDI.OutputOfCancelar) Implements ServicioCancelacionCFDI.CancelacionServiceSoap.CancelarCFDIAsync
            Return MyBase.Channel.CancelarCFDIAsync(rfc, serie, folio)
        End Function
        
        Public Function CancelarCFDI_UUID(ByVal rfc As String, ByVal uuid As String) As ServicioCancelacionCFDI.OutputOfCancelar Implements ServicioCancelacionCFDI.CancelacionServiceSoap.CancelarCFDI_UUID
            Return MyBase.Channel.CancelarCFDI_UUID(rfc, uuid)
        End Function
        
        Public Function CancelarCFDI_UUIDAsync(ByVal rfc As String, ByVal uuid As String) As System.Threading.Tasks.Task(Of ServicioCancelacionCFDI.OutputOfCancelar) Implements ServicioCancelacionCFDI.CancelacionServiceSoap.CancelarCFDI_UUIDAsync
            Return MyBase.Channel.CancelarCFDI_UUIDAsync(rfc, uuid)
        End Function
    End Class
End Namespace
