Public Class AforosLiquidadosEntidad
	Public Property contrato As Integer	'(int, null)
	Public Property importe As Decimal '(decimal(14,2), null)
	Public Property pago As Decimal	'(decimal(14,2), null)
	Public Property Cuenta As String '(varchar(15), null)
	Public Property folio As Integer '(int, null)
	Public Property movto As String	'(char(2), null)
	Public Property nombre As String '(char(100), null)
	Public Property cobranza As Integer	'(int, null)
	Public Property pagomatriz As Boolean '(bit, null)
	Public Property fecpago As DateTime	'(datetime, null)
	Public Property Moneda As String '(varchar(4), not null)
	Public Property userid As String '(char(15), null)
	Public Property numreccta As Integer '(int, null)
	Public Property idctabanco As Integer '(int, null)
	Public Property benef As String	'(char(100), null)
	Public Property producto As Integer	'(int, null)
	Public Property mone As Integer	'(int, null)
	Public Property id As Integer '(int, null)
	Public Property identidad As Integer '(int, null)
	Public Property aforo As Decimal '(decimal(14,2), null)
	Public Property descto As Decimal '(decimal(14,2), null)
	Public Property bonifica As Decimal	'(decimal(14,2), null)
	Public Property cartera As Decimal '(decimal(14,2), null)
	Public Property adeudos As Decimal '(decimal(14,2), null)
	Public Property numrec As Integer '(int, not null)
	Public Property ctabanco As String '(char(15), null)
	Public Property Origen As String '(char(35), null)
	Public Property shortname As String	'(char(20), null)
	Public Property clabe As String	'(char(18), null)
	Public Property timestart As DateTime '(datetime, null)
End Class
