Public Class LineasFactor
	Public Property producto As Integer?	'(int, null)
	Public Property prodDesc As String '(char(50), null)
	Public Property cliente As Integer?	'(int, null)
	Public Property clientet24 As Decimal? '(decimal(10,0), null)
	Public Property contrato As Integer	'(int, not null)
	Public Property Epo As String '(char(100), null)
	Public Property Estatus As String '(varchar(9), not null)
	Public Property fec_alta As DateTime? '(date, null)
	Public Property fec_Vence As DateTime? '(date, null)
	Public Property linea As Decimal? '(decimal(14,2), null)
	Public Property moneda As String '(varchar(3), not null)
	Public Property POperacion As DateTime?	'(date, not null)
	Public Property Registro As Integer?	'(int, null)
	Public Property Operado As Integer?	'(int, null)
	Public Property SonClientes As Integer '(int, null)
	Public Property Saldo As Decimal '(decimal(14,2), not null)
	Public Property promotor As Integer?	'(int, null)
	Public Property promo As String	'(char(50), null)
	Public Property idt24 As Decimal? '(decimal(16,0), null)
	Public Property activo As Boolean '(bit, null)
	Public Property Registro1 As DateTime? '(date, not null)
End Class
