Public Class sp_logfacturas

    Public Property fecha As Date
    Public Property serie As String
    Public Property folio As Integer
    Public Property sisfol As Integer
    Public Property identidad As Integer
    Public Property id As Integer
    Public Property contrato As Integer
    Public Property iva As Decimal
    Public Property importe As Decimal
    Public Property impresiones As Integer
    Public Property referencia As Integer
    Public Property remark As String
    Public Property cancelado As Boolean
    Public Property fcancelado As Date?
    Public Property moneda As Integer
    Public Property manual As Boolean
    Public Property void As Boolean
    Public Property emision As Date
    Public Property distrib As String
    Public Property sat As Decimal
    Public Property sustituir As Integer
    Public Property idfiscalpf As Integer
    Public Property idcesion As Integer?
    Public Property envio As Boolean
    Public Property foliooper As Integer
    Public Property ati As String
    Public Property nombre As String
    Public Property factura As String
    Public Property CANCEL As String
    Public Property Generated As String
    Public Property Divisa As String
    Public Property fauto As Date
    Public Property autoriza As String
    Public Property Erfc As String
    Public Property Erazon As String
    Public Property Edomicilio As String
    Public Property Enum1 As String
    Public Property eColonia As String
    Public Property Emunicipio As String
    Public Property estado As String
    Public Property Ecp As Integer
    Public Property eRefer As String
    Public Property elocalidad As String
    Public Property etelefono As String
    Public Property Rnombre As String
    Public Property Rrfc As String
    Public Property Rcalle As String
    Public Property Rnoext As String
    Public Property Rnoint As String
    Public Property rcolonia As String
    Public Property Rmunicipio As String
    Public Property Restado As String
    Public Property Rcp As Integer
    Public Property TDocSat As String
    Public Property RCodSuc As Integer
    Public Property Rnsucursal As String
    Public Property Cobiva As Decimal
    Public Property RecEmail As String
    Public Property Rtelefono As String
    Public Property ProdName As String
    Public Property ProdNum As String
    Public Property anio As Integer
    Public Property fec_aprob As Date
    Public Property paridad As Decimal
    Public Property Sdoc As String

End Class
