'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServicioWsFactura
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicioWsFactura.GetCypressServiceSoap")>  _
    Public Interface GetCypressServiceSoap
        
        'CODEGEN: Parameter 'getPdfResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getPdf", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getPdf(ByVal request As ServicioWsFactura.getPdfRequest) As ServicioWsFactura.getPdfResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getPdf", ReplyAction:="*")>  _
        Function getPdfAsync(ByVal request As ServicioWsFactura.getPdfRequest) As System.Threading.Tasks.Task(Of ServicioWsFactura.getPdfResponse)
        
        'CODEGEN: Parameter 'getXmlResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getXml", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getXml(ByVal request As ServicioWsFactura.getXmlRequest) As ServicioWsFactura.getXmlResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getXml", ReplyAction:="*")>  _
        Function getXmlAsync(ByVal request As ServicioWsFactura.getXmlRequest) As System.Threading.Tasks.Task(Of ServicioWsFactura.getXmlResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPdf", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getPdfRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public pdf As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pdf As String)
            MyBase.New
            Me.pdf = pdf
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getPdfResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getPdfResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public getPdfResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getPdfResult() As Byte)
            MyBase.New
            Me.getPdfResult = getPdfResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getXml", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getXmlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public xml As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal xml As String)
            MyBase.New
            Me.xml = xml
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="getXmlResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class getXmlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public getXmlResult() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getXmlResult() As Byte)
            MyBase.New
            Me.getXmlResult = getXmlResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface GetCypressServiceSoapChannel
        Inherits ServicioWsFactura.GetCypressServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetCypressServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicioWsFactura.GetCypressServiceSoap)
        Implements ServicioWsFactura.GetCypressServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioWsFactura_GetCypressServiceSoap_getPdf(ByVal request As ServicioWsFactura.getPdfRequest) As ServicioWsFactura.getPdfResponse Implements ServicioWsFactura.GetCypressServiceSoap.getPdf
            Return MyBase.Channel.getPdf(request)
        End Function
        
        Public Function getPdf(ByVal pdf As String) As Byte()
            Dim inValue As ServicioWsFactura.getPdfRequest = New ServicioWsFactura.getPdfRequest()
            inValue.pdf = pdf
            Dim retVal As ServicioWsFactura.getPdfResponse = CType(Me,ServicioWsFactura.GetCypressServiceSoap).getPdf(inValue)
            Return retVal.getPdfResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioWsFactura_GetCypressServiceSoap_getPdfAsync(ByVal request As ServicioWsFactura.getPdfRequest) As System.Threading.Tasks.Task(Of ServicioWsFactura.getPdfResponse) Implements ServicioWsFactura.GetCypressServiceSoap.getPdfAsync
            Return MyBase.Channel.getPdfAsync(request)
        End Function
        
        Public Function getPdfAsync(ByVal pdf As String) As System.Threading.Tasks.Task(Of ServicioWsFactura.getPdfResponse)
            Dim inValue As ServicioWsFactura.getPdfRequest = New ServicioWsFactura.getPdfRequest()
            inValue.pdf = pdf
            Return CType(Me,ServicioWsFactura.GetCypressServiceSoap).getPdfAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioWsFactura_GetCypressServiceSoap_getXml(ByVal request As ServicioWsFactura.getXmlRequest) As ServicioWsFactura.getXmlResponse Implements ServicioWsFactura.GetCypressServiceSoap.getXml
            Return MyBase.Channel.getXml(request)
        End Function
        
        Public Function getXml(ByVal xml As String) As Byte()
            Dim inValue As ServicioWsFactura.getXmlRequest = New ServicioWsFactura.getXmlRequest()
            inValue.xml = xml
            Dim retVal As ServicioWsFactura.getXmlResponse = CType(Me,ServicioWsFactura.GetCypressServiceSoap).getXml(inValue)
            Return retVal.getXmlResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicioWsFactura_GetCypressServiceSoap_getXmlAsync(ByVal request As ServicioWsFactura.getXmlRequest) As System.Threading.Tasks.Task(Of ServicioWsFactura.getXmlResponse) Implements ServicioWsFactura.GetCypressServiceSoap.getXmlAsync
            Return MyBase.Channel.getXmlAsync(request)
        End Function
        
        Public Function getXmlAsync(ByVal xml As String) As System.Threading.Tasks.Task(Of ServicioWsFactura.getXmlResponse)
            Dim inValue As ServicioWsFactura.getXmlRequest = New ServicioWsFactura.getXmlRequest()
            inValue.xml = xml
            Return CType(Me,ServicioWsFactura.GetCypressServiceSoap).getXmlAsync(inValue)
        End Function
    End Class
End Namespace
